@startuml
skinparam linetype ortho
top to bottom direction

' --- שכבת UI והמסכים ---
package "2. UI Layer (Screens & Components)" {
    class HomeView 
    class SmartCartView 
    class CartView 
    class AdminView 
    class HistoryView 
    class RegistrationView 
    class LoginView 
    class AdminProductTab 
    class AdminUserTab 
    class AdminOrdersTab 
    class AdminStatsTab 
    class ShopView 

    
package "3. Service Layer" 
{
    class WeatherService
    class ProductService
    class UserService
    class OrderService
    class SmartCartAlgoService
    class TagFieldService
    class ScoringService
}

CartView *-- OrderService
AdminView --> AdminProductTab
AdminView --> AdminUserTab
AdminView --> AdminOrdersTab
AdminView --> AdminStatsTab

ShopView *-- ProductService
SmartCartView *-- SmartCartAlgoService
SmartCartView *-- ScoringService
SmartCartView *-- TagFieldService
SmartCartView *-- ProductService

HistoryView *-- OrderService
WeatherRecommendationSection *-- WeatherService
WeatherRecommendationSection *-- ProductService
WeatherRecommendationSection *-- UserService
HomeView *-- WeatherService
HomeView *-- ProductService
HomeView *-- UserService
RegistrationView *-- UserService
LoginView *-- UserService

AdminUserTab *-- UserService
AdminProductTab *-- ProductService
AdminOrdersTab *-- OrderService
AdminStatsTab *-- OrderService
}
@enduml




